name: Nightly

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  publish-main:
    uses: ./.github/workflows/publish.yaml
    with:
      context: .
      registry: bikenow.vkw.tu-dresden.de
      image: ${{ github.repository }}
      branch: main
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}

  publish-stable:
    uses: ./.github/workflows/publish.yaml
    with:
      context: .
      registry: bikenow.vkw.tu-dresden.de
      image: ${{ github.repository }}
      branch: stable
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}

  publish-release:
    uses: ./.github/workflows/publish.yaml
    with:
      context: .
      registry: bikenow.vkw.tu-dresden.de
      image: ${{ github.repository }}
      branch: release
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}
